package org.com.meropasal.meropasalbackend.shop.enums;

/**
 * Created On : 2025 05 Feb 11:13 AM
 * Author : Monu Siddiki
 * Description :
 **/
public enum District {

    // Province 1
    TAPLEJUNG, PANCHTHAR, ILAM, JHAPA, MORANG, SUNSARI, DHANKUTA, TERHATHUM, SANKHUWASABHA, BOJHPUR, SOLUKHUMBU, KHOTANG, OKHALDHUNGA, UDAYAPUR,

    // Madhesh Province
    SAPTARI, SIRAHA, DHANUSA, MAHOTTARI, SARLAHI, BARA, PARSA, RAUTAHAT,

    // Bagmati Province
    SINDHULI, RAMECHHAP, DOLAKHA, SINDHUPALCHOK, KAVREPALANCHOK, LALITPUR, BHAKTAPUR, KATHMANDU, NUWAKOT, RASUWA, DHADING, MAKAWANPUR, CHITWAN,

    // Gandaki Province
    GORKHA, LAMJUNG, TANAHU, SYANGJA, KASKI, MANANG, MUSTANG, MYAGDI, PARBAT, BAGLUNG, NAWALPUR,

    // Lumbini Province
    NAWALPARASI, RUPANDEHI, KAPILVASTU, ARGHAKHANCHI, GULMI, PALPA, PARASI, ROLPA, PYUTHAN, DANG, BANKA, BARDIYA,

    // Karnali Province
    DOLPA, HUMLA, MUGU, KALIKOT, JUMLA, DAILEKH, JAJARKOT, RUKUM_EAST, SURKHET, SALYAN,

    // Sudurpashchim Province
    BAJURA, BAJHANG, DOTI, ACHHAM, KAILALI, KANCHANPUR, DADHELDHURA, BAITADI, DARCHULA;


}
